const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('bridge', {
  minimize:             () => ipcRenderer.send('window-minimize'),
  maximize:             () => ipcRenderer.send('window-maximize'),
  close:                () => ipcRenderer.send('window-close'),
  newtabUrl:            'divo://newtab',
  settingsUrl:          'divo://settings',
  toggleFullscreen:     () => ipcRenderer.send('toggle-fullscreen'),
  focusWebview:         (id) => ipcRenderer.send('focus-webview', id),
  openFile:             (p)  => ipcRenderer.send('open-file', p),
  openDlFolder:         ()   => ipcRenderer.send('open-dl-folder'),
  answerPermission:     (key, granted) => ipcRenderer.send('answer-permission', key, granted),
  onDlStart:            (cb) => ipcRenderer.on('dl-start',          (_, d) => cb(d)),
  onDlUpdate:           (cb) => ipcRenderer.on('dl-update',         (_, d) => cb(d)),
  onDlDone:             (cb) => ipcRenderer.on('dl-done',           (_, d) => cb(d)),
  onOpenNewTab:         (cb) => ipcRenderer.on('open-new-tab',      (_, u) => cb(u)),
  onFullscreenChange:   (cb) => ipcRenderer.on('fullscreen-change', (_, v) => cb(v)),
  onPermissionRequest:  (cb) => ipcRenderer.on('permission-request',(_, d) => cb(d)),
  adblockStatus: ()        => ipcRenderer.invoke('adblock-status'),
  adblockToggle: (v)       => ipcRenderer.invoke('adblock-toggle', v),
  importChromeBookmarks: () => ipcRenderer.invoke('import-chrome-bookmarks'),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  importBookmarksHtml:   () => ipcRenderer.invoke('import-bookmarks-html'),
  getDownloadPath:    () => ipcRenderer.invoke('get-download-path'),
  pickDownloadPath:   () => ipcRenderer.invoke('pick-download-path'),
  webDarkModeStatus: () => ipcRenderer.invoke('web-dark-mode-status'),
  webDarkModeToggle: (v) => ipcRenderer.invoke('web-dark-mode-toggle', v),
  onWebviewShortcut:    (cb) => ipcRenderer.on('webview-shortcut',  (_, d) => cb(d)),
  onUpdateAvailable:    (cb) => ipcRenderer.on('update-available',    (_, d) => cb(d)),
  onUpdateProgress:     (cb) => ipcRenderer.on('update-progress',     (_, p) => cb(p)),
  installUpdate:        (url) => ipcRenderer.invoke('install-update',  url),
  isDefaultBrowser:     ()    => ipcRenderer.invoke('is-default-browser'),
  setDefaultBrowser:    ()    => ipcRenderer.invoke('set-default-browser'),
  onNotDefaultBrowser:  (cb)  => ipcRenderer.on('not-default-browser', () => cb()),
})